
###

POST http://46.101.193.219:8081/auth/authenticate
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "122333"
}

###

POST http://46.101.193.219:8081/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "122333"
}


###

# http://localhost:3001/auth/user
http://46.101.193.219:8081/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDkwMTRldmMwMDAwcXUxZXVxcGF1b2FqIiwiaWF0IjoxNjY1MjQyNjkxLCJleHAiOjE2NjUzMjkwOTF9.9CEqo8uV1y9avGfq48JUpKvyGG5p79Z_IOQst8keJWw

###
