
###

POST http://172.104.229.79:8081/auth/authenticate
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "122333"
}

###

POST http://172.104.229.79:8081/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "user-2@nikolav.rs",
  "password": "122333"
}


###

# http://localhost:3001/auth/user
http://172.104.229.79:8081/auth/user
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbDkwcTc3ODcwMDAyb3kwdHBzZmh3bDhnIiwiaWF0IjoxNjY1MjgyNDk2LCJleHAiOjE2NjUzNjg4OTZ9.QpVIfEBvKxRK66KLDHzPoPi2dZ2i_RslhjCqaoU2bhE

###
