
###

POST http://159.89.111.224:8081/auth/authenticate
Accept: application/json
Content-Type: application/json

{
  "email": "admin@nikolav.rs",
  "password": "122333"
}

###

POST http://localhost:3001/auth/register
Accept: application/json
Content-Type: application/json

{
  "email": "user-007@email.com",
  "password": "122333"
}


###

# http://localhost:3001/auth/user
http://159.89.111.224:8081/auth/user
Accept: application/json
Authorization: Bearer -

###
