
###

POST http://localhost:3001/email/plaintext
Accept: application/json
Content-Type: application/json
Authorization: Bearer -

{
  "to": "admin@nikolav.rs",
  "from": "admin@nikolav.rs",
  "subject": "promo.subject --test",
  "message": "promo.message --test"
}

###
